robots:
  mur620c:
  - /mur620c/UR10_r/UR10_r_enable
  - /mur620c/UR10_r/controller_stopper
  - /mur620c/UR10_r/ewellix_tlt_node_r
  - /mur620c/UR10_r/gripper_interface
  - /mur620c/UR10_r/pose_composer
  - /mur620c/UR10_r/ros_control_controller_spawner
  - /mur620c/UR10_r/ros_control_stopped_spawner
  - /mur620c/UR10_r/rosnode_killer
  - /mur620c/UR10_r/ur_calibrated_pose_pub_node
  - /mur620c/UR10_r/ur_hardware_interface
  - /mur620c/UR10_r/ur_hardware_interface/ur_robot_state_helper
  - /mur620c/UR10_r/ur_twist_limiter
  - /mur620c/b_rep117_laser_filter
  - /mur620c/bms_can_node
  - /mur620c/f_rep117_laser_filter
  - /mur620c/fake_mir_joint_publisher
  - /mur620c/light_cmd_transcode
  - /mur620c/light_cmd_transcode_local
  - /mur620c/mir_battery_state_publisher
  - /mur620c/mir_bridge
  - /mur620c/mir_pose_simple
  - /mur620c/move_base_node
  - /mur620c/move_group
  - /mur620c/remove_tf_frames
  - /mur620c/rgb_control
  - /mur620c/robot_state_publisher
  - /mur620c/tf_remove_state_publisher_frames
updated_at: '2025-11-26 15:53:39'
